A.22 assignment
ravin-imm/PSI pull request #5
Opened 2023-05-17 15:15 UTC by ravin-imm

2023-05-22 04:00 UTC, sdinesh-90 requested changes

2023-05-22 04:00 UTC, sdinesh-90 commented on PSICover/PSICover.cs
> +         int nHits = 0;
Review from Arvind: Minor style guideline. I generally use lowercase c as a prefix to indicate a count. So this variable would be called `cHits`.

2023-05-22 04:00 UTC, sdinesh-90 commented on PSICover/PSICover.cs
> +            if (block.ELine != block.SLine) {
If condition is not needed.

2023-05-22 04:08 UTC, ravin-imm commented on PSICover/PSICover.cs
> +            if (block.ELine != block.SLine) {
@sdinesh-90 : I think we need to consider the start and the end columns when it is a single line block. Can you please elaborate on the change required?

2023-05-22 04:17 UTC, sdinesh-90 commented on PSICover/PSICover.cs
> +            if (block.ELine != block.SLine) {
For every line of code, we need to figure out start and end column. So, based on first or last line, we could set the column index appropriately.
Even though this uses two if condition for every loop, it seems to be precise.

2023-05-24 10:56 UTC, sdinesh-90 approved these changes

2023-05-24 10:56 UTC, sdinesh-90 commented
Looks fine

2023-05-24 10:56 UTC, closed without merging